package repos
data class repos (
    var id: Int,
    var node_id: String,
    var name: String,
    var full_name: String,
    var private: Boolean,
    var description: String,
    var fork: Boolean,
    var url: String,
    var homepage:String,
    var size: Int,
    var stargazers_count: Int,
    var watchers_count: Int,
    var language: String,
    var has_issues: Boolean,
    var has_projects: Boolean,
    var has_downloads: Boolean,
    var forks_count: Int,
    var mirror_url: String,
    var archived: Boolean,
    var disabled: Boolean,
    var open_issues_count: Int,
    var licente: String,
    var allow_forking: String,
    var is_template: Boolean,
    var topics: List<String>,
    var visibility: String,
    var forks: Int,
    var open_issues: Int,
    var watchers: Int,
    var default_branch: String,
    var template_clone_token: String,
    var network_count: Int,
    var subscribers_count: Int
)